### ISSUE TITLE
Missing testrunner in travis build

### ISSUE THREAD

**Issue by cmccully** [astropy/astroscrappy#3]
@eteq @embray @astrofrog Do you know why these travis builds are failing with the following error:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "astroscrappy/_astropy_init.py", line 106, in test
    test_runner = _get_test_runner()
  File "astroscrappy/_astropy_init.py", line 28, in _get_test_runner
    from astropy.tests.helper import TestRunner
ImportError: cannot import name TestRunner
The command "python setup.py $SETUP_CMD" exited with 1.

**Comment by astrofrog** [comment]
I think it's due to

https://github.com/astropy/astropy/pull/4020

Suggested fix for Astropy in https://github.com/astropy/astropy/pull/4224
