### ISSUE TITLE
Unable to install astroscrappy with pip-install

### ISSUE THREAD

**Issue by jbcurtin** [astropy/astroscrappy#45]
Hello, I'm unable to install `astroscrappy` with,
`pip install astroscrappy`

```
Building wheels for collected packages: astroscrappy
  Building wheel for astroscrappy (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: ./workspace/spacetelescope/notebooks/env2/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/_6/w75l5bpn5tgbwm_jg8z1m07h0002ch/T/pip-install-pgqkrk1n/astroscrappy/setup.py'"'"'; __file__='"'"'/private/var/folders/_6/
w75l5bpn5tgbwm_jg8z1m07h0002ch/T/pip-install-pgqkrk1n/astroscrappy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/_6/w7
5l5bpn5tgbwm_jg8z1m07h0002ch/T/pip-wheel-j2aryhmz --python-tag cp37
       cwd: /private/var/folders/_6/w75l5bpn5tgbwm_jg8z1m07h0002ch/T/pip-install-pgqkrk1n/astroscrappy/
  Complete output (59 lines):
  OpenMP was not found. astroscrappy will be compiled without OpenMP. (Use the "-v" option of setup.py for more details.)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.7-x86_64-3.7
  creating build/lib.macosx-10.7-x86_64-3.7/astroscrappy
  copying astroscrappy/conftest.py -> build/lib.macosx-10.7-x86_64-3.7/astroscrappy
  copying astroscrappy/version.py -> build/lib.macosx-10.7-x86_64-3.7/astroscrappy
  copying astroscrappy/_astropy_init.py -> build/lib.macosx-10.7-x86_64-3.7/astroscrappy
  copying astroscrappy/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/astroscrappy
  copying astroscrappy/cython_version.py -> build/lib.macosx-10.7-x86_64-3.7/astroscrappy
  creating build/lib.macosx-10.7-x86_64-3.7/astroscrappy/tests
  copying astroscrappy/tests/test_utils.py -> build/lib.macosx-10.7-x86_64-3.7/astroscrappy/tests
  copying astroscrappy/tests/test_astroscrappy.py -> build/lib.macosx-10.7-x86_64-3.7/astroscrappy/tests
  copying astroscrappy/tests/fake_data.py -> build/lib.macosx-10.7-x86_64-3.7/astroscrappy/tests
  copying astroscrappy/tests/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/astroscrappy/tests
  copying astroscrappy/tests/test_cleaning.py -> build/lib.macosx-10.7-x86_64-3.7/astroscrappy/tests
  copying astroscrappy/tests/setup_package.py -> build/lib.macosx-10.7-x86_64-3.7/astroscrappy/tests
  creating build/lib.macosx-10.7-x86_64-3.7/astroscrappy/utils
  copying astroscrappy/utils/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/astroscrappy/utils
  copying astroscrappy/utils/setup_package.py -> build/lib.macosx-10.7-x86_64-3.7/astroscrappy/utils
  copying astroscrappy/astroscrappy.c -> build/lib.macosx-10.7-x86_64-3.7/astroscrappy
  copying astroscrappy/_compiler.c -> build/lib.macosx-10.7-x86_64-3.7/astroscrappy
  copying astroscrappy/utils/image_utils.c -> build/lib.macosx-10.7-x86_64-3.7/astroscrappy/utils
  copying astroscrappy/utils/medutils.c -> build/lib.macosx-10.7-x86_64-3.7/astroscrappy/utils
  copying astroscrappy/utils/median_utils.c -> build/lib.macosx-10.7-x86_64-3.7/astroscrappy/utils
  copying astroscrappy/utils/imutils.c -> build/lib.macosx-10.7-x86_64-3.7/astroscrappy/utils
  copying astroscrappy/tests/coveragerc -> build/lib.macosx-10.7-x86_64-3.7/astroscrappy/tests
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/_6/w75l5bpn5tgbwm_jg8z1m07h0002ch/T/pip-install-pgqkrk1n/astroscrappy/setup.py", line 148, in <module>
      **package_info
    File "./workspace/spacetelescope/notebooks/env2/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "./anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "./anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "./anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "./workspace/spacetelescope/notebooks/env2/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "./anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "./anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "./anaconda3/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "./anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "./anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/_6/w75l5bpn5tgbwm_jg8z1m07h0002ch/T/pip-install-pgqkrk1n/astroscrappy/.eggs/astropy_helpers-2.0.10-py3.7.egg/astropy_helpers/commands/build_ext.py", line 296, in run
      np_include = get_numpy_include_path()
    File "/private/var/folders/_6/w75l5bpn5tgbwm_jg8z1m07h0002ch/T/pip-install-pgqkrk1n/astroscrappy/.eggs/astropy_helpers-2.0.10-py3.7.egg/astropy_helpers/utils.py", line 89, in get_numpy_include_path
      import numpy
  ModuleNotFoundError: No module named 'numpy'
  ----------------------------------------
  ERROR: Failed building wheel for astroscrappy
  Running setup.py clean for astroscrappy
Failed to build astroscrappy
Installing collected packages: numpy, astropy, astroscrappy
  Running setup.py install for astroscrappy ... done
Successfully installed astropy-3.2.1 astroscrappy-1.0.8 numpy-1.17.2
```

**Comment by NadezdaYa** [comment]
I have the same problem. Please, write how have you solved it?

**Comment by jbcurtin** [comment]
hey @NadezdaYa, it seems to be installing fine for me now,

```
$ virtualenv -p $(which python3) env
$ source env/bin/activate
$ pip install astroscrappy -U
```

Depending on your version of python, you may have to pre-install the dependencies, `numpy` and `astropy`
https://github.com/astropy/astroscrappy/blob/master/setup.cfg#L52

```
$ virtualenv -p $(which python3) env
$ source env/bin/activate
$ pip install numpy astropy astroscrappy -U
```

does this help?
