### ISSUE TITLE
ah_bootstrap.py from astropy-headers distributed with tarball needs to be updated

### ISSUE THREAD

**Issue by JohnPritchard** [astropy/astroscrappy#50]
When I tried to build astroscrappy-1.0.8 (from PyPi) as a MacPort package it fails with the following error:

`
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    import ah_bootstrap
  File "/opt/local/var/macports/build/_opt_vjpd_macports_ports_python_py-vjpd-astroscrappy/py36-vjpd-astroscrappy/work/astroscrappy-1.0.8/ah_bootstrap.py", line 920, in <module>
    BOOTSTRAPPER = _Bootstrapper.main()
  File "/opt/local/var/macports/build/_opt_vjpd_macports_ports_python_py-vjpd-astroscrappy/py36-vjpd-astroscrappy/work/astroscrappy-1.0.8/ah_bootstrap.py", line 223, in main
    bootstrapper.run()
  File "/opt/local/var/macports/build/_opt_vjpd_macports_ports_python_py-vjpd-astroscrappy/py36-vjpd-astroscrappy/work/astroscrappy-1.0.8/ah_bootstrap.py", line 321, in run
    dist = method()
  File "/opt/local/var/macports/build/_opt_vjpd_macports_ports_python_py-vjpd-astroscrappy/py36-vjpd-astroscrappy/work/astroscrappy-1.0.8/ah_bootstrap.py", line 389, in get_local_directory_dist
    upgrade = self._do_upgrade(dist)
  File "/opt/local/var/macports/build/_opt_vjpd_macports_ports_python_py-vjpd-astroscrappy/py36-vjpd-astroscrappy/work/astroscrappy-1.0.8/ah_bootstrap.py", line 569, in _do_upgrade
    return self._do_download(version=upgrade.version)
  File "/opt/local/var/macports/build/_opt_vjpd_macports_ports_python_py-vjpd-astroscrappy/py36-vjpd-astroscrappy/work/astroscrappy-1.0.8/ah_bootstrap.py", line 554, in _do_download
    raise Exception(msg.format(DIST_NAME, source, repr(e)))
Exception: Error retrieving astropy-helpers from PyPI:
DistutilsError('the `allow-hosts` option is not supported when using pip to install requirements.',)
`

This can be fixed by updating ah_bootstrap.py from the latest distribution of astro-headers (v4.0.1).

Best regards
John Pritchard

P.S. Why is the latest version on PyPi 1.0.8 but only 1.0.5 on GitHub? It's a little disconcerting...

**Comment by cmccully** [comment]
@JohnPritchard You are indeed correct. We are getting ready for a new release that follows APE 17 https://docs.astropy.org/projects/package-template/en/latest/ape17.html. I could actually make that release relatively quickly before we sort out adding spectroscopy if that would be useful. 

Don't worry about the difference 1.0.5 and 1.0.8. That was a mistake on my part when uploading to pypi. I missed updating the version name on github. The code is identical.

**Comment by mattip** [comment]
When you do, please update the cython used to process the pyx files. Even better: release wheels in addition to the source tarball to prevent everyone who uses your package needing to compile it. One easy way to create wheels is to use the [cibuildwheel](https://cibuildwheel.readthedocs.io/en/stable/) project in a [github action](https://cibuildwheel.readthedocs.io/en/stable/setup/).

**Comment by juliotux** [comment]
Thanks @mattip . This may fix #55 too.

**Comment by saimn** [comment]
Now that we use PEP517 and have cython in the `pyproject.toml` we should probably not ship the generated c files. This way cython would always compile them when installing.

Having wheels would be nice as well, but there is the question of OpenMP. I'm not sure if that's a good idea to have wheels with shared libs linked to OpenMP by default, maybe on Linux ? @mattip - do you know what other projects do for this ?

**Comment by mattip** [comment]
I am not quite sure if you want to go down the path of shipping OpenMP so/dlls, so that may indeed be a blocker for creating wheels. If you do want to explore it,  one strategy is to rename the so/dll something like astrocscrappy_openmp.so and link to that, so it will not conflict with other implementations that may be loaded into the program space by other users of OpenMP. This is what NumPy does with the OpenBLAS it ships in wheels.

**Comment by saimn** [comment]
Interesting, thanks. I will try to have a look at some point. I see that scikit-image is building with OpenMP for MacOS but not for Linux (https://github.com/scikit-image/scikit-image/blob/master/.github/workflows/cibuildwheel.yml#L47-L50).

**Comment by saimn** [comment]
Version 1.1.0 is out, and no more uses astropy-helpers.
